name: Build my app

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Build and release new apk
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.5' 
      - run: flutter upgrade    
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3.1.2
        with:
          path: build/app/outputs/apk/release/*
      
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - uses: actions/upload-artifact@v3.1.2
        with:
          path: build/app/outputs/apk/release/*